; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files.
; File: highlights.scm
; === BEGIN EXPR ===
(pattern_expression) @regexp

[
  (json_number_literal)
  (numeric_literal)
  (json_boolean_literal)
  (json_null_literal)
] @number

(json_object_literal_pair
  (json_string_literal) @typeParameter)

[
  (json_string_literal)
  (string_literal)
] @string

(system_defined_function) @function.defaultLibrary

; this is because . is grouped into system_defined_function
; and I want the dots to be the same color
(class_method_call
  "." @function.defaultLibrary)

(byref_arg
  "." @function.defaultLibrary)

(oref_chain_segment
  "." @function.defaultLibrary)

(sql_field_modifier) @keyword.modification

[
  (property_name)
  (oref_parameter)
  (sql_field_identifier)
] @property

(method_name) @method

[
  (routine_name)
  (class_name)
] @type

(macro_function) @function

(macro_constant) @enum

(objectscript_identifier) @variable

[
  (ssvn)
  (system_defined_variable)
  "$$"
] @variable.defaultLibrary

[
  (gvn)
  (objectscript_identifier_special)
  (instance_variable)
] @property

(method_arg) @parameter

; === END EXPR ===
; === BEGIN CORE ===
(macro_arg) @property

(macro_value) @enum

(macro_def) @keyword.definition

[
  (keyword_pound_define)
  (keyword_pound_def1arg)
  (keyword_pound_if)
  (keyword_pound_elseif)
  (keyword_pound_else)
  (keyword_pound_endif)
  (keyword_pound_ifdef)
  (keyword_pound_ifndef)
  (keyword_dim)
  (keyword_pound_import)
  (keyword_pound_include)
  (keyword_pound_delay)
  (locktype)
  (tag_end_if)
] @keyword.definition

[
  (keyword_as)
  (keyword_of)
  (keyword_public)
  (keyword_private)
  (keyword_methodimpl)
  (device_keywords)
  (close_parameter_option_value)
  (keyword_clear)
  (keyword_on)
  (keyword_off)
  (keyword_all)
  (keyword_ext)
  (keyword_stepmethod)
  (keyword_destruct)
] @keyword.modification

[
  (keyword_zbreak)
  (keyword_debug)
  (zbreak_command_option)
  (keyword_trace)
  (keyword_step)
  (keyword_nostep)
  (keyword_stepmethod)
  (keyword_errortrap)
  (keyword_interrupt)
  (keyword_zkill)
  (keyword_zn)
  (keyword_zsu)
  (keyword_ztrap)
  (keyword_zz)
  (keyword_print)
  (keyword_zprint)
  (keyword_set)
  (keyword_write)
  (keyword_zwrite)
  (keyword_do)
  (keyword_do_old)
  (keyword_kill)
  (keyword_lock)
  (keyword_read)
  (keyword_open)
  (keyword_close)
  (keyword_use)
  (keyword_new)
  (keyword_job)
  (keyword_merge)
  (keyword_goto)
  (keyword_halt_or_hang)
  (keyword_halt)
  (keyword_hang)
  (keyword_tcommit)
  (keyword_trollback)
  (keyword_tstart)
  (keyword_xecute)
  (keyword_view)
  (keyword_zremove)
  (command_keyword)
  (keyword_zload)
  (keyword_for)
  (keyword_while)
  (keyword_continue)
  (keyword_quit)
  (keyword_break)
  (keyword_return)
  (keyword_if)
  (keyword_old_if)
  (keyword_elseif)
  (keyword_else)
  (keyword_oldelse)
  (keyword_throw)
  (keyword_try)
  (keyword_catch)
  (keyword_pound_pound_super)
  (keyword_pound_pound_class)
] @function.defaultLibrary

[
  (keyword_embedded_html)
  (keyword_embedded_xml)
  (keyword_embedded_sql_amp)
  (keyword_embedded_sql_hash)
  (keyword_js)
] @keyword

[
  (embedded_js_special_case_complete)
  (embedded_sql_marker)
  (embedded_sql_reverse_marker)
  (html_marker)
  (html_marker_reversed)
] @event

[
  (line_comment_1)
  (line_comment_2)
  (line_comment_3)
  (line_comment_4)
  (block_comment)
  (inline_comment)
  (pound_if_special_case_else)
  (pound_if_special_case)
  (argumentless_inline_comment)
] @comment

(tag) @method

"--" @operator

(variable_datatype
  "." @function.defaultLibrary)

(method_call
  "." @function.defaultLibrary)

; === END CORE ===
; === BEGIN LOCAL ===
(iris_username) @keyword.definition

[
  (keyword_import)
  (keyword_include)
  (keyword_includegenerator)
  (keyword_method)
  (keyword_classmethod)
  (keyword_class)
  (keyword_extends)
  (keyword_property)
  (keyword_relationship)
  (keyword_foreignkey)
  (keyword_parameter)
  (keyword_projection)
  (keyword_index)
  (keyword_query)
  (keyword_trigger)
  (keyword_xdata)
  (keyword_storage)
] @function.defaultLibrary

[
  (method_keyword_codemode_expression)
  (call_method_keyword)
  (extent_index_keyword)
  (method_keyword)
  (class_keyword)
  (query_keyword)
  (trigger_keyword)
  (method_keyword_language)
  (relationship_keyword)
  (foreignkey_keyword)
  (parameter_keyword)
  (projection_keyword)
  (index_keyword)
  (xdata_keyword)
  (xdata_keyword_mimetype)
  (property_keyword)
  (keyword_not)
  (keyword_references)
  (keyword_byref)
  (keyword_output)
] @keyword.modification

(documatic_line) @comment

[
  (query_name)
  (trigger_name)
  (relationship_name)
  (foreignkey_name)
  (parameter_name)
  (projection_name)
  (index_name)
  (xdata_name)
  (storage_name)
  (xml_identifier)
  (index_property)
] @property

[
  (return_type)
  (keyword_list)
  (parameter_type)
  (index_type)
  (index_property_type)
  (typename)
] @type.defaultLibrary

; === END LOCAL ===
